# Generated by Django 2.2.16 on 2022-05-15 07:57

import django.db.models.deletion
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'genre_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='genres', to='reviews.Genre'
                    )
                ),
                (
                    'title_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='titles', to='reviews.Title'
                    )
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={
                'ordering': ('-pub_date', '-review_id', '-id'),
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии'
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи'
            },
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, verbose_name='токен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(
                blank=True, max_length=6, verbose_name='Код подтверждения'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('user', 'user'), ('moderator', 'moderator'),
                    ('admin', 'admin')
                ],
                default='user', max_length=16, verbose_name='Роль пользователя'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                help_text='Required. 150 char or fewer. Lett, and dig only.',
                max_length=150, unique=True,
                validators=[reviews.models.my_username_validator],
                verbose_name='Username'
            ),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
