# Generated by Django 2.2.16 on 2022-05-15 09:46

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220515_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 char or fewer. Letters, and digits only.', max_length=150, unique=True, validators=[reviews.models.my_username_validator], verbose_name='Username'),
        ),
    ]
