# Generated by Django 2.2.16 on 2022-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220513_2049'),
        ('reviews', '0002_auto_20220513_1658'),
    ]

    operations = [
    ]
